# Generated by Django 2.0.5 on 2018-06-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180602_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='countries',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
