# Generated by Django 2.0.5 on 2018-06-02 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180602_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='countries',
            new_name='country',
        ),
    ]
